//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace MapReader
{
	public class LayerTile
	{
		public bool flippedH;
		public bool flippedV;
		public bool flippedD;
		public int gid;
		
		public LayerTile (int gid, bool d, bool h, bool v) {
			this.gid = gid;
			this.flippedD = d;
			this.flippedH = h;
			this.flippedV = v;
		}
	}
}

