//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.18444
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml;
using System.Collections.Generic;
using UnityEngine;

namespace MapReader
{
	public class MapObject {

		public int x;
		public int y;
		public int width;
		public int height;

		public MapObject (XmlNode node) {
			this.x = int.Parse(node.Attributes["x"].Value);
			this.y = int.Parse(node.Attributes["y"].Value);
			this.width = int.Parse(node.Attributes["width"].Value);
			this.height = int.Parse(node.Attributes["height"].Value);
		}
	}
}

